import { StyleSheet } from 'react-native';
import { verticalScale, scale } from '../../../utils/scaling';
import { fontStyles } from '../../../utils/fontStyles';
import { alignment, colors } from '../../../utils';

const styles = StyleSheet.create({
  container: {
    flexGrow: 1,
    backgroundColor: colors.white,
  },
  maincontainer: {
    ...alignment.Pmedium,
  },
  backgroundCurvedContainer: {
    backgroundColor: colors.btncolor,
    height: 200,
    width: '100%',
    position: 'absolute',
    top: 0,
    zIndex: 0,
  },
  protractorShape: {
    backgroundColor: colors.white,
    height: 500,
    width: 1000,
    borderTopLeftRadius: 500,
    borderTopRightRadius: 500,
    position: 'absolute',
    top: 80,
    alignSelf: 'center',
    zIndex: 1,
    overflow: 'hidden',
  },
  topIconsRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: verticalScale(5),
    paddingHorizontal: scale(5),
    zIndex: 3,
  },
  circle: {
    width: 60,
    height: 60,
    borderRadius: 30,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'rgba(47, 47, 47, 0.5)',
    
  },
  profileSection: {
    alignItems: 'center',
    marginBottom: verticalScale(20),
    zIndex: 2,
    marginTop: -60
  },
  profileImage: {
    width: verticalScale(100),
    height: verticalScale(100),
    borderRadius: verticalScale(50),
    borderWidth: 5,
    borderColor: colors.greenColor,
  },
  editIcon: {
    position: 'absolute',
    bottom: verticalScale(40),
    right: verticalScale(100),
    backgroundColor: colors.greenColor,
    borderRadius: verticalScale(20),
    padding: scale(5),
  },
  profileName: {
    fontFamily: fontStyles.PoppinsSemiBold,
    fontSize: verticalScale(20),
    marginTop: verticalScale(10),
    color: colors.fontMainColor,
  },
  statsContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginVertical: 20,
    paddingHorizontal: 15,
    paddingVertical: 10,
    borderWidth: 1,
    borderColor: colors.grayLinesColor,
    borderRadius: 20,
    backgroundColor: colors.white,
    shadowColor: '#000000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.25,
    shadowRadius: 6,
    elevation: 6,
    zIndex: 2,
  },
  stat: {
    flex: 1,
    alignItems: 'center',
    paddingVertical: 10,
    borderRightWidth: 1,
    borderRightColor: '#d3d3d3',
  },
  statLast: {
    flex: 1,
    alignItems: 'center',
    paddingVertical: 10,
  },
  statNumber: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#333',
  },
  statLabel: {
    fontSize: 18,
    color: '#000000',
    fontWeight: 'bold',
  },
  settingsSection: {
    marginTop: verticalScale(20),
    zIndex: 2,
  },
  settingsItem: {
    backgroundColor: colors.backgroudGray,
    borderRadius: 40,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: verticalScale(16),
    paddingVertical: verticalScale(16),
    marginBottom: verticalScale(10),
  },
  settingsItemContent: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  settingsItemText: {
    fontFamily: fontStyles.PoppinsRegular,
    fontSize: verticalScale(16),
    marginLeft: scale(10),
    color: colors.fontMainColor,
  },
  // Share Modal Styles
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  shareModalContainer: {
    backgroundColor: colors.white,
    borderRadius: 25,
    padding: verticalScale(20),
    marginHorizontal: scale(20),
    width: '90%',
    maxWidth: 400,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 10,
    },
    shadowOpacity: 0.25,
    shadowRadius: 20,
    elevation: 10,
  },
  modalHandle: {
    width: 40,
    height: 5,
    backgroundColor: '#E0E0E0',
    borderRadius: 3,
    alignSelf: 'center',
    marginBottom: verticalScale(20),
  },
  shareModalTitle: {
    fontSize: verticalScale(20),
    fontWeight: 'bold',
    textAlign: 'center',
    color: colors.fontMainColor,
    marginBottom: verticalScale(20),
    fontFamily: fontStyles.PoppinsSemiBold,
  },
  sharePreviewContainer: {
    alignItems: 'center',
    marginBottom: verticalScale(25),
    paddingVertical: verticalScale(20),
    backgroundColor: colors.backgroudGray,
    borderRadius: 20,
  },
  sharePreviewImage: {
    width: verticalScale(80),
    height: verticalScale(80),
    borderRadius: verticalScale(40),
    borderWidth: 3,
    borderColor: colors.greenColor,
    marginBottom: verticalScale(10),
  },
  sharePreviewName: {
    fontSize: verticalScale(18),
    fontWeight: 'bold',
    color: colors.fontMainColor,
    marginBottom: verticalScale(5),
    fontFamily: fontStyles.PoppinsSemiBold,
  },
  sharePreviewUsername: {
    fontSize: verticalScale(14),
    color: colors.fontSecondColor,
    fontFamily: fontStyles.PoppinsRegular,
  },
  shareModalButtons: {
    gap: verticalScale(12),
  },
  shareModalButton: {
    backgroundColor: colors.btncolor,
    borderRadius: 15,
    paddingVertical: verticalScale(15),
    paddingHorizontal: verticalScale(20),
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: colors.btncolor,
    shadowOffset: {
      width: 0,
      height: 4,
    },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 5,
  },
  shareModalButtonText: {
    color: colors.white,
    fontSize: verticalScale(16),
    fontWeight: '600',
    marginLeft: scale(8),
    fontFamily: fontStyles.PoppinsSemiBold,
  },
  cancelModalButton: {
    backgroundColor: 'transparent',
    borderRadius: 15,
    paddingVertical: verticalScale(15),
    paddingHorizontal: verticalScale(20),
    borderWidth: 1,
    borderColor: colors.grayLinesColor,
  },
  cancelModalButtonText: {
    color: colors.fontMainColor,
    fontSize: verticalScale(16),
    fontWeight: '600',
    textAlign: 'center',
    fontFamily: fontStyles.PoppinsSemiBold,
  },
});

export default styles;
